version: 2.1

jobs:
  build:
    working_directory: ~/Final-Year-Frontend
    docker:
      #create docker image
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: Final-Year-Frontend-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run: npm install
      #save the node modules for use in both
      - save_cache:
          key: Final-Year-Frontend-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - "node_modules"
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js