import { CompletionState } from '../enums/completionState';
import { TradeType } from '../enums/trade-types';
import { Job } from '../models/job';

export class JobTestData {

    public jobs: Job[] = [
        {
            id: '1',
            address: '',
            budget: 1,
            completionState: CompletionState.closed,
            conclusionDate: 1,
            description: '',
            issueDate: 1,
            issueUid: '',
            lngLat: { lat: 1, lng: 1 },
            postcode: '',
            quotes: [],
            reviewScore: 1,
            reviewed: { trader: true, user: true },
            timeframe: '',
            title: 'test Title 1',
            trade: TradeType.builder,
            userReviewScore: '1',
            workCandidates: [],
        },
        {
            id: '1',
            address: '',
            budget: 1,
            completionState: CompletionState.active,
            conclusionDate: 1,
            description: '',
            issueDate: 1,
            issueUid: '',
            lngLat: { lat: 1, lng: 1 },
            postcode: '',
            quotes: [],
            reviewScore: 1,
            reviewed: { trader: true, user: true },
            timeframe: '',
            title: 'test Title 2',
            trade: TradeType.builder,
            userReviewScore: '1',
            workCandidates: [],
        },
        {
            id: '1',
            address: '',
            budget: 1,
            completionState: CompletionState.active,
            conclusionDate: 1,
            description: '',
            issueDate: 1,
            issueUid: '',
            lngLat: { lat: 1, lng: 1 },
            postcode: '',
            quotes: [],
            reviewScore: 1,
            reviewed: { trader: true, user: true },
            timeframe: '',
            title: 'test Title 2.5',
            trade: TradeType.builder,
            userReviewScore: '',
            workCandidates: [],
        },
    ]
}